### PR TITLE
fakerData

### PR DESCRIPTION
**Pull request by tiffanyjalovec**
Can I get honest feedback on the fakerData?
I am seeding 100 reviews for the first 5 items, then seeding 10 reviews per item.
This seed script is only for 1000 items.

### CODE REVIEW

**Comment by jbalbin3** [comment]
I noticed you are writing everything to the results array in memory.  You might want to change that to writing to csv file and writing it out the data in csv format.

**Comment by Try-Try-Again** [comment]
> I noticed you are writing everything to the results array in memory. You might want to change that to writing to csv file and writing it out the data in csv format.

Ahh, I missed that! Some reviewer I am :\

**Comment by tiffanyjalovec** [comment]
> I noticed you are writing everything to the results array in memory. You might want to change that to writing to csv file and writing it out the data in csv format.

Yes that is next on the list!

**Comment by tiffanyjalovec** [comment]
> you have repeated code blocks that could be factored out (3 strikes rule), Otherwise, it looks good :)

Thank you! That is helpful. Good point!

**Pull request merged**
